
import javax.swing.JFrame;

/**
 *
 * @author strainchampsclothilde
 */
public class OptionsDlg extends javax.swing.JDialog {

    private int choixOpt;// attribut pour le choix de l'option choisie
    private int nbCol;// attribut pour le nombre de colonne de la carte
    private int nbNum;// attribut pour le nombre de numéro dans la carte
    private int nb;
    private boolean ok;// indicateur pour la boîte de dialogue
    
    public OptionsDlg(java.awt.Frame parent, boolean modal, boolean ca, int nc, int nn) {
        super(parent, modal);// appel du constructeur de la classe ancêtre ici JDilaog
        initComponents();// construction de l’interface faite par l’EDI
        remplirComboCol();// méthode pour remplir la comboBox avec les numéro de colonne
        this.ok= false;// on fixe la fermeture de la boîte de dialogue à false
        BQuine.setSelected(true);// le bouton radio BQuine est sélectionner par défaut
        this.choixOpt = 1;// choix est fixé à 1 par défaut
        if(!ca){// si aucune carte n'a été acheter avant
            this.nbCol = 5;// on fixe par défaut le nombre de colonne à 5
            this.nbNum = 5;// on fixe par défaut le nombre de numéros à 5
        }
        else{// si des cartes on déjà été acheté
            this.nbCol = nc;// on fixe le nombre de colonne avec le paramètre (équivalent à celui des cartes déjà achetées)
            this.nbNum = nn;// on fixe le nombre de numéros avec le paramètre (équivalent à celui des cartes déjà achetées)
            ComboNbCol.setSelectedIndex(this.nbCol-5);
            ComboNbCol.setEnabled(false);
            NbNumero.setText(String.valueOf(this.nbNum));// on écrit dans le textField le nombre de numéros
            NbNumero.setEnabled(false);// que l'on rend non modifiable
            Message.setText( "Nb de colonnes et de numéros non modifiables");// le label message affiche...
        }
    }

    private OptionsDlg(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    // accesseurs en lecture
    public int getChoix(){
        return this.choixOpt;
    }
    public int getNbCol(){
        return this.nbCol;
    }
    public int getNbNum(){
        return this.nbNum;
    }
    public boolean getOk(){
        return this.ok;
    }
    //accesseurs en écriture
    public void setChoix(int n ){
        this.choixOpt = n;
    }
    public void setNbCol(int n ){
        this.nbCol = n;
    }
    public void setNbNum(int n ){
        this.nbNum = n;
    }
    

    private void remplirComboCol(){// méthode pour remplir la comboBox avec les nb dispo de colonne
        ComboNbCol.addItem("Choisir");
        ComboNbCol.addItem("5");
        ComboNbCol.addItem("6");
        ComboNbCol.addItem("7");
        ComboNbCol.addItem("8");
        ComboNbCol.addItem("9");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PanCentre = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BQuine = new javax.swing.JRadioButton();
        BDQuine = new javax.swing.JRadioButton();
        BCartonPlein = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanCase1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ComboNbCol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        NbNumero = new javax.swing.JTextField();
        PanCase2 = new javax.swing.JPanel();
        PanCaseMsg = new javax.swing.JPanel();
        Message = new javax.swing.JLabel();
        PanBouton = new javax.swing.JPanel();
        BAnnuler = new javax.swing.JButton();
        BValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setFont(new java.awt.Font("Zapf Dingbats", 1, 24)); // NOI18N
        LTitre.setText("Options du jeu");
        PanTitre.add(LTitre);

        getContentPane().add(PanTitre, java.awt.BorderLayout.NORTH);

        PanCentre.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setText("Comment voulez-vous jouer ?");
        jPanel1.add(jLabel1);

        buttonGroup1.add(BQuine);
        BQuine.setText("Quine - Une ligne complète");
        BQuine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQuineActionPerformed(evt);
            }
        });
        jPanel1.add(BQuine);

        buttonGroup1.add(BDQuine);
        BDQuine.setText("Double Quine - Deux lignes complètes");
        BDQuine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDQuineActionPerformed(evt);
            }
        });
        jPanel1.add(BDQuine);

        buttonGroup1.add(BCartonPlein);
        BCartonPlein.setText("Carton plein - Trois lignes complètes");
        BCartonPlein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCartonPleinActionPerformed(evt);
            }
        });
        jPanel1.add(BCartonPlein);

        PanCentre.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setText("Configuration des cartons");
        jPanel2.add(jLabel2);

        javax.swing.GroupLayout PanCase1Layout = new javax.swing.GroupLayout(PanCase1);
        PanCase1.setLayout(PanCase1Layout);
        PanCase1Layout.setHorizontalGroup(
            PanCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        PanCase1Layout.setVerticalGroup(
            PanCase1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(PanCase1);

        jLabel3.setText("Combiens de colonnes ?");
        jPanel2.add(jLabel3);

        ComboNbCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNbColActionPerformed(evt);
            }
        });
        jPanel2.add(ComboNbCol);

        jLabel4.setText("Combiens de numéros ?");
        jPanel2.add(jLabel4);

        NbNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbNumeroActionPerformed(evt);
            }
        });
        jPanel2.add(NbNumero);

        javax.swing.GroupLayout PanCase2Layout = new javax.swing.GroupLayout(PanCase2);
        PanCase2.setLayout(PanCase2Layout);
        PanCase2Layout.setHorizontalGroup(
            PanCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        PanCase2Layout.setVerticalGroup(
            PanCase2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel2.add(PanCase2);

        PanCaseMsg.setLayout(new java.awt.GridLayout());

        Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanCaseMsg.add(Message);

        jPanel2.add(PanCaseMsg);

        PanCentre.add(jPanel2);

        getContentPane().add(PanCentre, java.awt.BorderLayout.CENTER);

        PanBouton.setLayout(new java.awt.GridLayout(1, 2));

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        PanBouton.add(BAnnuler);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        PanBouton.add(BValider);

        getContentPane().add(PanBouton, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        int choix = BQuine.isSelected() ? 1 : BDQuine.isSelected() ? 2 : 3;// si BQuine est coché choix=1, si c'est BDQuine choix =2, sinon choix =3
        this.nbNum = Integer.valueOf(NbNumero.getText());// le nombre de numéros est égal à la valeur écrite par l'utilisateur dans le textField (on la convertit en entier car c'est une chaîne de caractères)
        int ind = ComboNbCol.getSelectedIndex();// indice 
        String s = ComboNbCol.getSelectedItem().toString();
        if(ind!=0)
            this.nbCol=Integer.valueOf(s);
        
        if(this.nbNum < 5 || this.nbNum > this.nbCol * 3)
            Message.setText("Entrées Impossibles !");
        else{
            this.nbNum = Integer.valueOf(NbNumero.getText()); 
            this.choixOpt = choix;
            this.nbCol=Integer.valueOf(s);
            this.ok = true;
            this.setVisible(false);
            this.dispose();
        }
        
    }//GEN-LAST:event_BValiderActionPerformed

    private void ComboNbColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNbColActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_ComboNbColActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BAnnulerActionPerformed

    private void BQuineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuineActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_BQuineActionPerformed

    private void BDQuineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDQuineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDQuineActionPerformed

    private void BCartonPleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCartonPleinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCartonPleinActionPerformed

    private void NbNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NbNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionsDlg dialog = new OptionsDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JRadioButton BCartonPlein;
    private javax.swing.JRadioButton BDQuine;
    private javax.swing.JRadioButton BQuine;
    private javax.swing.JButton BValider;
    private javax.swing.JComboBox<String> ComboNbCol;
    private javax.swing.JLabel LTitre;
    private javax.swing.JLabel Message;
    private javax.swing.JTextField NbNumero;
    private javax.swing.JPanel PanBouton;
    private javax.swing.JPanel PanCase1;
    private javax.swing.JPanel PanCase2;
    private javax.swing.JPanel PanCaseMsg;
    private javax.swing.JPanel PanCentre;
    private javax.swing.JPanel PanTitre;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
